<?php

return [
    'starter' => [
        'name' => 'Starter',
        'stripe_price_id' => env('STRIPE_STARTER_PRICE_ID'),
        'price_monthly' => 49,
        'limits' => [
            'workspaces' => 1,
            'social_accounts' => 5,
            'ai_credits' => 100,
            'team_members' => 2,
            'scheduled_posts' => 50,
            'keywords_tracked' => 20,
            'contacts' => 500,
        ],
        'features' => [
            'unified_inbox',
            'social_publishing',
            'basic_analytics',
            'ai_writing',
        ],
    ],
    'growth' => [
        'name' => 'Growth',
        'stripe_price_id' => env('STRIPE_GROWTH_PRICE_ID'),
        'price_monthly' => 99,
        'limits' => [
            'workspaces' => 3,
            'social_accounts' => 15,
            'ai_credits' => 500,
            'team_members' => 5,
            'scheduled_posts' => 200,
            'keywords_tracked' => 100,
            'contacts' => 5000,
        ],
        'features' => [
            'unified_inbox',
            'social_publishing',
            'advanced_analytics',
            'ai_writing',
            'ai_images',
            'seo_toolkit',
            'crm',
            'review_management',
        ],
    ],
    'agency' => [
        'name' => 'Agency',
        'stripe_price_id' => env('STRIPE_AGENCY_PRICE_ID'),
        'price_monthly' => 249,
        'limits' => [
            'workspaces' => 25,
            'social_accounts' => 100,
            'ai_credits' => 2000,
            'team_members' => 25,
            'scheduled_posts' => -1,
            'keywords_tracked' => 500,
            'contacts' => 50000,
        ],
        'features' => [
            'unified_inbox',
            'social_publishing',
            'advanced_analytics',
            'ai_writing',
            'ai_images',
            'seo_toolkit',
            'crm',
            'review_management',
            'ads_management',
            'white_label',
            'client_portal',
            'report_builder',
        ],
    ],
];
